#!/bin/bash
#
# Grep agama journald.out.log for external rpm commands executed by libzypp
#
# Author:  Stefan Hundhammer <shundhammer@suse.com>
# License: GPL V2

infile=$*
journal="journald.out.log"

if [ -z "$infile" ]; then
    if [ -f $journal ]; then
        infile=$journal
    else
        echo "FATAL: No infile." 1>&2
        exit 1
    fi
fi

grep -h -E "Executing.*'rpm'.*'-[Ui]'" $infile | \
    sed -E \
        -e 's:^[A-Z][a-z]+ [0-9]+ ::' \
        -e 's: [A-Za-z]+.* agama-web-server.* .(-[Ui]). .*/mnt/var/cache/zypp/packages/: rpm \1  :' \
        -e 's/(-[Ui]).*:/\1  /' \
        -e "s:'::"
