#!/bin/bash
#
# Grep y2log for external rpm commands executed by libzypp
#
# Author:  Stefan Hundhammer <shundhammer@suse.com>
# License: GPL V2

infile=$*

if [ -z "$infile" ]; then
    if [ -f y2log-full.log ]; then
        infile=y2log-full.log
    else
        infile=y2log
    fi
fi

grep -h -E "zypp::exec.*Executing.*'rpm'.*'-U'" $infile | \
    sed -e 's:<[0-9]>.*/: rpm -U  :' \
        -e "s:'$::"
