#!/bin/sh
#
# Split y2logs into separate files, one for each YaST invocation.
#
# Author:  Stefan Hundhammer <shundhammer@suse.com>
# License: GPL V2

src=$1

if [ -z "$src" ]; then
    echo
    echo "Usage: $0 <y2log-name>"
    echo
    exit 1
fi

# Remove old split files
rm -f y2-??.log

# Split
csplit -z -q -f 'y2-' -b '%02d.log' $src '/.*y2base called with.*/' '{*}'

# Show YaST invocation line for each result file
grep 'y2base called with' y2-??.log | sed -e 's/\.log:/.log:  /' -e 's/<1>.*y2base/ y2base/'
