#!/bin/sh
#
# Strip irregular lines from one or more y2log files in-place;
# leave only those that match the standard log line pattern:
#
#   2024-02-30 14:07:42 <0> myhost(4711) [Ruby]
#
# Author:  Stefan Hundhammer <shundhammer@suse.com>
# License: GPL V2


y2logs=$*

if [ -z "$y2logs" ]; then
    echo
    echo "Usage: $0 <y2-01.log> [y2-02.log] ..."
    echo
    echo "  Strip irregular lines from one or more y2log files in-place;"
    echo "  leave only those that match the standard log line pattern:"
    echo
    echo "2024-02-30 14:07:42 <0> myhost(4711) [Ruby]"
    echo
    exit 1
fi

echo
echo "++ Lines before:"
wc -l $y2logs

echo
echo "Stripping irregular lines..."

for log in $y2logs ; do
    # match  2024-02-30 14:07:42 <0> myhost(4711) [Ruby]
    
    perl -n -i.bak -e 'print if /^((20\d\d-\d\d-\d\d )?\d\d:\d\d:\d\d)|(\/usr\/|\/mnt\/)|(Backtrace)/;' $log
done

echo
echo "-- Lines after:"
wc -l $y2logs
echo
