#!/bin/sh
#
# Strip the date and hostname part from y2log headers in-place.
#
#   2024-02-30 14:07:42 <0> myhost(4711) [Ruby]
#
# Author:  Stefan Hundhammer <shundhammer@suse.com>
# License: GPL V2


y2logs=$*

if [ -z "$y2logs" ]; then
    echo
    echo "Usage: $0 <y2-01.log> [y2-02.log] ..."
    echo
    echo #  Strip the date and hostname part from y2log headers in-place."
    echo
    echo "2024-02-30 14:07:42 <1> myhost(4711) [Ruby]"
    echo "->"
    echo "14:07:42 <1> [Ruby]"
    echo
    echo
    exit 1
fi

echo
echo "Stripping date, hostname, PID from y2log line headers..."
echo

for log in $y2logs ; do
    # sample line:  2024-02-30 14:07:42 <1> myhost(4711) [Ruby]

    perl -p -i.bak                                      \
      -e 's/^20\d\d-\d\d-\d\d //;'                      \
      -e 's/(\d\d:\d\d:\d\d <\d\>) (\S+) (\[)/$1 $3/;'  \
      $log

      # Intentionally stripping both parts separately in case
      # one or the other part was already stripped.
done

