#!/bin/sh
#
# Merge all y2log-*.gz files and y2log to one single y2log-full.log file
#
# Author:  Stefan Hundhammer <shundhammer@suse.com>
# License: GPL V2

result=y2log-full.log

echo "Creating $result"
rm -f $result

# Add gzipp'ed y2logs in reverse order (y2log-5.gz is the oldest),
# then the unzipped latest y2log

for log in $( /bin/ls -r y2log-[0-9].gz ) y2log ; do
    if [ -f $log ]; then
        echo "Adding $log"
        zcat -f $log >>$result
    fi
done

echo ""

echo -n "Size:  "
du -h $result

echo ""
echo -n "Lines: "
wc -l $result
echo ""

