#!/bin/sh
#
# Strip the hostname/pid part from the line header of one or more y2log files in-place.
#
#   2024-02-30 14:07:42 <0> myhost(4711) [Ruby]
#
# Author:  Stefan Hundhammer <shundhammer@suse.com>
# License: GPL V2


y2logs=$*

if [ -z "$y2logs" ]; then
    echo
    echo "Usage: $0 <y2-01.log> [y2-02.log] ..."
    echo
    echo "  Strip the hostname/pid part from the line header y2log files in-place."
    echo
    echo "2024-02-30 14:07:42 <1> myhost(4711) [Ruby]"
    echo "->"
    echo "2024-02-30 14:07:42 <1> [Ruby]"
    echo
    echo
    exit 1
fi

echo
echo "Stripping hostname/pid from line headers..."
echo

for log in $y2logs ; do
    # sample line:  2024-02-30 14:07:42 <1> myhost(4711) [Ruby]
    
    perl -p -i.bak -e 's/(\d\d:\d\d:\d\d <\d\>) (\S+) (\[)/$1 $3/' $log
done

